const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  selectVault:       ()  => ipcRenderer.invoke('select-vault'),
  getVaultPath:      ()  => ipcRenderer.invoke('get-vault-path'),
  loadGraph:         ()  => ipcRenderer.invoke('load-graph'),
  readNote:          (id)=> ipcRenderer.invoke('read-note', id),
  openInObsidian:    (id)=> ipcRenderer.invoke('open-in-obsidian', id),
  openInExplorer:    (id)=> ipcRenderer.invoke('open-in-explorer', id),
  toggleAlwaysOnTop: (v) => ipcRenderer.invoke('toggle-always-on-top', v),
  getAlwaysOnTop:    ()  => ipcRenderer.invoke('get-always-on-top'),
  setStartup:        (v) => ipcRenderer.invoke('set-startup', v),
  getStartup:        ()  => ipcRenderer.invoke('get-startup'),
  savePrefs:         (p) => ipcRenderer.invoke('save-prefs', p),
  loadPrefs:         ()  => ipcRenderer.invoke('load-prefs'),
  closeApp:          ()  => ipcRenderer.invoke('close-app'),
  minimizeApp:       ()  => ipcRenderer.invoke('minimize-app'),
  toggleFullscreen:  ()  => ipcRenderer.invoke('toggle-fullscreen'),
  getFullscreen:     ()  => ipcRenderer.invoke('get-fullscreen'),
  onFullscreenChange:(cb)=> ipcRenderer.on('fullscreen-changed', (_, v) => cb(v)),
  onVaultChanged:    (cb)=> ipcRenderer.on('vault-changed', () => cb()),
  onParseProgress:   (cb)=> ipcRenderer.on('parse-progress', (_, p) => cb(p)),
  exportPng:         (d) => ipcRenderer.invoke('export-png', d),
  checkUpdate:       ()  => ipcRenderer.invoke('check-update'),
  openUrl:           (u) => ipcRenderer.invoke('open-url', u),
  getHotkey:         ()  => ipcRenderer.invoke('get-hotkey'),
  setHotkey:         (a) => ipcRenderer.invoke('set-hotkey', a),
});
